# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Python33\ui\HarfNotunuHesapla.ui'
#
# Created: Thu Mar  7 21:08:34 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(342, 281)
        Dialog.setMinimumSize(QtCore.QSize(342, 281))
        Dialog.setMaximumSize(QtCore.QSize(342, 281))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        Dialog.setFont(font)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 321, 261))
        self.groupBox.setMinimumSize(QtCore.QSize(321, 261))
        self.groupBox.setMaximumSize(QtCore.QSize(321, 261))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.sinif_ortalamasi_label = QtGui.QLabel(self.groupBox)
        self.sinif_ortalamasi_label.setGeometry(QtCore.QRect(20, 160, 117, 25))
        self.sinif_ortalamasi_label.setObjectName(_fromUtf8("sinif_ortalamasi_label"))
        self.hamnot_label_2 = QtGui.QLabel(self.groupBox)
        self.hamnot_label_2.setGeometry(QtCore.QRect(19, 200, 71, 25))
        self.hamnot_label_2.setObjectName(_fromUtf8("hamnot_label_2"))
        self.hamnot_label = QtGui.QLabel(self.groupBox)
        self.hamnot_label.setGeometry(QtCore.QRect(95, 200, 51, 25))
        self.hamnot_label.setObjectName(_fromUtf8("hamnot_label"))
        self.hesapla_pushButton = QtGui.QPushButton(self.groupBox)
        self.hesapla_pushButton.setGeometry(QtCore.QRect(220, 30, 90, 28))
        self.hesapla_pushButton.setObjectName(_fromUtf8("hesapla_pushButton"))
        self.sonuc_label_2 = QtGui.QLabel(self.groupBox)
        self.sonuc_label_2.setGeometry(QtCore.QRect(19, 230, 51, 25))
        self.sonuc_label_2.setObjectName(_fromUtf8("sonuc_label_2"))
        self.sonuc_label = QtGui.QLabel(self.groupBox)
        self.sonuc_label.setGeometry(QtCore.QRect(95, 230, 51, 25))
        self.sonuc_label.setObjectName(_fromUtf8("sonuc_label"))
        self.ybn_label_2 = QtGui.QLabel(self.groupBox)
        self.ybn_label_2.setGeometry(QtCore.QRect(159, 200, 51, 25))
        self.ybn_label_2.setObjectName(_fromUtf8("ybn_label_2"))
        self.ybn_label = QtGui.QLabel(self.groupBox)
        self.ybn_label.setGeometry(QtCore.QRect(205, 200, 51, 25))
        self.ybn_label.setObjectName(_fromUtf8("ybn_label"))
        self.temizle_pushButton = QtGui.QPushButton(self.groupBox)
        self.temizle_pushButton.setGeometry(QtCore.QRect(220, 70, 90, 28))
        self.temizle_pushButton.setAutoDefault(False)
        self.temizle_pushButton.setObjectName(_fromUtf8("temizle_pushButton"))
        self.sinav_groupBox = QtGui.QGroupBox(self.groupBox)
        self.sinav_groupBox.setGeometry(QtCore.QRect(10, 10, 61, 141))
        self.sinav_groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.sinav_groupBox.setObjectName(_fromUtf8("sinav_groupBox"))
        self.odev_label = QtGui.QLabel(self.sinav_groupBox)
        self.odev_label.setGeometry(QtCore.QRect(11, 50, 50, 25))
        self.odev_label.setAlignment(QtCore.Qt.AlignCenter)
        self.odev_label.setObjectName(_fromUtf8("odev_label"))
        self.qlabel = QtGui.QLabel(self.sinav_groupBox)
        self.qlabel.setGeometry(QtCore.QRect(11, 20, 50, 25))
        self.qlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.qlabel.setObjectName(_fromUtf8("qlabel"))
        self.final_label = QtGui.QLabel(self.sinav_groupBox)
        self.final_label.setGeometry(QtCore.QRect(11, 110, 50, 25))
        self.final_label.setAlignment(QtCore.Qt.AlignCenter)
        self.final_label.setObjectName(_fromUtf8("final_label"))
        self.vize_label = QtGui.QLabel(self.sinav_groupBox)
        self.vize_label.setGeometry(QtCore.QRect(11, 80, 50, 25))
        self.vize_label.setAlignment(QtCore.Qt.AlignCenter)
        self.vize_label.setObjectName(_fromUtf8("vize_label"))
        self.yuzde_groupBox = QtGui.QGroupBox(self.groupBox)
        self.yuzde_groupBox.setGeometry(QtCore.QRect(75, 10, 61, 141))
        self.yuzde_groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.yuzde_groupBox.setObjectName(_fromUtf8("yuzde_groupBox"))
        self.quiz_yuzde_lineEdit = QtGui.QLineEdit(self.yuzde_groupBox)
        self.quiz_yuzde_lineEdit.setGeometry(QtCore.QRect(10, 21, 40, 25))
        self.quiz_yuzde_lineEdit.setMaxLength(3)
        self.quiz_yuzde_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.quiz_yuzde_lineEdit.setObjectName(_fromUtf8("quiz_yuzde_lineEdit"))
        self.odev_yuzde_lineEdit = QtGui.QLineEdit(self.yuzde_groupBox)
        self.odev_yuzde_lineEdit.setGeometry(QtCore.QRect(10, 51, 40, 25))
        self.odev_yuzde_lineEdit.setMaxLength(3)
        self.odev_yuzde_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.odev_yuzde_lineEdit.setObjectName(_fromUtf8("odev_yuzde_lineEdit"))
        self.vize_yuzde_lineEdit = QtGui.QLineEdit(self.yuzde_groupBox)
        self.vize_yuzde_lineEdit.setGeometry(QtCore.QRect(10, 81, 40, 25))
        self.vize_yuzde_lineEdit.setMaxLength(3)
        self.vize_yuzde_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.vize_yuzde_lineEdit.setObjectName(_fromUtf8("vize_yuzde_lineEdit"))
        self.final_yuzde_lineEdit = QtGui.QLineEdit(self.yuzde_groupBox)
        self.final_yuzde_lineEdit.setGeometry(QtCore.QRect(10, 111, 40, 25))
        self.final_yuzde_lineEdit.setMaxLength(3)
        self.final_yuzde_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.final_yuzde_lineEdit.setObjectName(_fromUtf8("final_yuzde_lineEdit"))
        self.not_groupBox = QtGui.QGroupBox(self.groupBox)
        self.not_groupBox.setGeometry(QtCore.QRect(140, 10, 61, 141))
        self.not_groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.not_groupBox.setObjectName(_fromUtf8("not_groupBox"))
        self.quiz_lineEdit = QtGui.QLineEdit(self.not_groupBox)
        self.quiz_lineEdit.setGeometry(QtCore.QRect(10, 21, 40, 25))
        self.quiz_lineEdit.setMaxLength(3)
        self.quiz_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.quiz_lineEdit.setObjectName(_fromUtf8("quiz_lineEdit"))
        self.odev_lineEdit = QtGui.QLineEdit(self.not_groupBox)
        self.odev_lineEdit.setGeometry(QtCore.QRect(10, 51, 40, 25))
        self.odev_lineEdit.setMaxLength(3)
        self.odev_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.odev_lineEdit.setObjectName(_fromUtf8("odev_lineEdit"))
        self.final_lineEdit = QtGui.QLineEdit(self.not_groupBox)
        self.final_lineEdit.setGeometry(QtCore.QRect(10, 111, 40, 25))
        self.final_lineEdit.setMaxLength(3)
        self.final_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.final_lineEdit.setObjectName(_fromUtf8("final_lineEdit"))
        self.vize_lineEdit = QtGui.QLineEdit(self.not_groupBox)
        self.vize_lineEdit.setGeometry(QtCore.QRect(10, 81, 40, 25))
        self.vize_lineEdit.setMaxLength(3)
        self.vize_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.vize_lineEdit.setObjectName(_fromUtf8("vize_lineEdit"))
        self.ortalama_lineEdit = QtGui.QLineEdit(self.groupBox)
        self.ortalama_lineEdit.setGeometry(QtCore.QRect(140, 161, 50, 25))
        self.ortalama_lineEdit.setMaxLength(5)
        self.ortalama_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.ortalama_lineEdit.setObjectName(_fromUtf8("ortalama_lineEdit"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Harf Notunu Hesaplayıcı", None))
        self.sinif_ortalamasi_label.setText(_translate("Dialog", "Sınıf Ortalaması :", None))
        self.hamnot_label_2.setText(_translate("Dialog", "Ham Not :", None))
        self.hamnot_label.setText(_translate("Dialog", "...", None))
        self.hesapla_pushButton.setText(_translate("Dialog", "Hesapla", None))
        self.hesapla_pushButton.setShortcut(_translate("Dialog", "Return", None))
        self.sonuc_label_2.setText(_translate("Dialog", "Sonuç :", None))
        self.sonuc_label.setText(_translate("Dialog", "...", None))
        self.ybn_label_2.setText(_translate("Dialog", "YBN :", None))
        self.ybn_label.setText(_translate("Dialog", "...", None))
        self.temizle_pushButton.setText(_translate("Dialog", "Temizle", None))
        self.temizle_pushButton.setShortcut(_translate("Dialog", "Backspace", None))
        self.sinav_groupBox.setTitle(_translate("Dialog", "Sınav", None))
        self.odev_label.setText(_translate("Dialog", "Ödev :", None))
        self.qlabel.setText(_translate("Dialog", "Quiz :", None))
        self.final_label.setText(_translate("Dialog", "Final :", None))
        self.vize_label.setText(_translate("Dialog", "Vize :", None))
        self.yuzde_groupBox.setTitle(_translate("Dialog", "Yüzde", None))
        self.vize_yuzde_lineEdit.setText(_translate("Dialog", "40", None))
        self.final_yuzde_lineEdit.setText(_translate("Dialog", "60", None))
        self.not_groupBox.setTitle(_translate("Dialog", "Not", None))

