# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Python33\ui\OrtalamaHesapla.ui'
#
# Created: Sun Mar 10 23:24:33 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(636, 498)
        Dialog.setMinimumSize(QtCore.QSize(636, 498))
        Dialog.setMaximumSize(QtCore.QSize(636, 650))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        Dialog.setFont(font)
        Dialog.setFocusPolicy(QtCore.Qt.TabFocus)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setHorizontalSpacing(9)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.ortalama_sonuc_label = QtGui.QLabel(Dialog)
        self.ortalama_sonuc_label.setMinimumSize(QtCore.QSize(0, 20))
        self.ortalama_sonuc_label.setMaximumSize(QtCore.QSize(16777215, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.ortalama_sonuc_label.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ortalama_sonuc_label.setFont(font)
        self.ortalama_sonuc_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ortalama_sonuc_label.setObjectName(_fromUtf8("ortalama_sonuc_label"))
        self.gridLayout.addWidget(self.ortalama_sonuc_label, 1, 2, 1, 1)
        self.scrollArea = QtGui.QScrollArea(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(490, 222))
        self.scrollArea.setFrameShape(QtGui.QFrame.Box)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 472, 478))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setContentsMargins(-1, 0, -1, 6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.basliklar_horizontalLayout = QtGui.QHBoxLayout()
        self.basliklar_horizontalLayout.setSpacing(0)
        self.basliklar_horizontalLayout.setObjectName(_fromUtf8("basliklar_horizontalLayout"))
        self.ders_no_label = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ders_no_label.sizePolicy().hasHeightForWidth())
        self.ders_no_label.setSizePolicy(sizePolicy)
        self.ders_no_label.setMinimumSize(QtCore.QSize(0, 0))
        self.ders_no_label.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.ders_no_label.setFont(font)
        self.ders_no_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ders_no_label.setObjectName(_fromUtf8("ders_no_label"))
        self.basliklar_horizontalLayout.addWidget(self.ders_no_label)
        self.ders_adi_label = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ders_adi_label.sizePolicy().hasHeightForWidth())
        self.ders_adi_label.setSizePolicy(sizePolicy)
        self.ders_adi_label.setMinimumSize(QtCore.QSize(0, 0))
        self.ders_adi_label.setMaximumSize(QtCore.QSize(127, 16777215))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.ders_adi_label.setFont(font)
        self.ders_adi_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ders_adi_label.setObjectName(_fromUtf8("ders_adi_label"))
        self.basliklar_horizontalLayout.addWidget(self.ders_adi_label)
        self.kredi_label = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kredi_label.sizePolicy().hasHeightForWidth())
        self.kredi_label.setSizePolicy(sizePolicy)
        self.kredi_label.setMaximumSize(QtCore.QSize(68, 16777215))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.kredi_label.setFont(font)
        self.kredi_label.setAlignment(QtCore.Qt.AlignCenter)
        self.kredi_label.setObjectName(_fromUtf8("kredi_label"))
        self.basliklar_horizontalLayout.addWidget(self.kredi_label)
        self.harf_notu_label = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.harf_notu_label.sizePolicy().hasHeightForWidth())
        self.harf_notu_label.setSizePolicy(sizePolicy)
        self.harf_notu_label.setMaximumSize(QtCore.QSize(65, 16777215))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.harf_notu_label.setFont(font)
        self.harf_notu_label.setAlignment(QtCore.Qt.AlignCenter)
        self.harf_notu_label.setObjectName(_fromUtf8("harf_notu_label"))
        self.basliklar_horizontalLayout.addWidget(self.harf_notu_label)
        self.kredi_harf_notu_label = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kredi_harf_notu_label.sizePolicy().hasHeightForWidth())
        self.kredi_harf_notu_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.kredi_harf_notu_label.setFont(font)
        self.kredi_harf_notu_label.setAlignment(QtCore.Qt.AlignCenter)
        self.kredi_harf_notu_label.setObjectName(_fromUtf8("kredi_harf_notu_label"))
        self.basliklar_horizontalLayout.addWidget(self.kredi_harf_notu_label)
        self.verticalLayout.addLayout(self.basliklar_horizontalLayout)
        self.ders_horizontalLayout_1 = QtGui.QHBoxLayout()
        self.ders_horizontalLayout_1.setObjectName(_fromUtf8("ders_horizontalLayout_1"))
        self.ders_no_label_1 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ders_no_label_1.sizePolicy().hasHeightForWidth())
        self.ders_no_label_1.setSizePolicy(sizePolicy)
        self.ders_no_label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.ders_no_label_1.setObjectName(_fromUtf8("ders_no_label_1"))
        self.ders_horizontalLayout_1.addWidget(self.ders_no_label_1)
        self.ders_adi_lineEdit_1 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ders_adi_lineEdit_1.sizePolicy().hasHeightForWidth())
        self.ders_adi_lineEdit_1.setSizePolicy(sizePolicy)
        self.ders_adi_lineEdit_1.setText(_fromUtf8(""))
        self.ders_adi_lineEdit_1.setAlignment(QtCore.Qt.AlignCenter)
        self.ders_adi_lineEdit_1.setObjectName(_fromUtf8("ders_adi_lineEdit_1"))
        self.ders_horizontalLayout_1.addWidget(self.ders_adi_lineEdit_1)
        self.kredi_comboBox_1 = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.kredi_comboBox_1.setObjectName(_fromUtf8("kredi_comboBox_1"))
        self.kredi_comboBox_1.addItem(_fromUtf8(""))
        self.kredi_comboBox_1.addItem(_fromUtf8(""))
        self.kredi_comboBox_1.addItem(_fromUtf8(""))
        self.kredi_comboBox_1.addItem(_fromUtf8(""))
        self.kredi_comboBox_1.addItem(_fromUtf8(""))
        self.kredi_comboBox_1.addItem(_fromUtf8(""))
        self.kredi_comboBox_1.addItem(_fromUtf8(""))
        self.kredi_comboBox_1.addItem(_fromUtf8(""))
        self.kredi_comboBox_1.addItem(_fromUtf8(""))
        self.kredi_comboBox_1.addItem(_fromUtf8(""))
        self.kredi_comboBox_1.addItem(_fromUtf8(""))
        self.ders_horizontalLayout_1.addWidget(self.kredi_comboBox_1)
        self.harf_notu_comboBox_1 = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.harf_notu_comboBox_1.setObjectName(_fromUtf8("harf_notu_comboBox_1"))
        self.harf_notu_comboBox_1.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_1.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_1.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_1.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_1.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_1.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_1.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_1.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_1.addItem(_fromUtf8(""))
        self.ders_horizontalLayout_1.addWidget(self.harf_notu_comboBox_1)
        self.sonuc_label_1 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.sonuc_label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.sonuc_label_1.setObjectName(_fromUtf8("sonuc_label_1"))
        self.ders_horizontalLayout_1.addWidget(self.sonuc_label_1)
        self.verticalLayout.addLayout(self.ders_horizontalLayout_1)
        self.ders_horizontalLayout_2 = QtGui.QHBoxLayout()
        self.ders_horizontalLayout_2.setObjectName(_fromUtf8("ders_horizontalLayout_2"))
        self.ders_no_label_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ders_no_label_2.sizePolicy().hasHeightForWidth())
        self.ders_no_label_2.setSizePolicy(sizePolicy)
        self.ders_no_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.ders_no_label_2.setObjectName(_fromUtf8("ders_no_label_2"))
        self.ders_horizontalLayout_2.addWidget(self.ders_no_label_2)
        self.ders_adi_lineEdit_2 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ders_adi_lineEdit_2.sizePolicy().hasHeightForWidth())
        self.ders_adi_lineEdit_2.setSizePolicy(sizePolicy)
        self.ders_adi_lineEdit_2.setText(_fromUtf8(""))
        self.ders_adi_lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.ders_adi_lineEdit_2.setObjectName(_fromUtf8("ders_adi_lineEdit_2"))
        self.ders_horizontalLayout_2.addWidget(self.ders_adi_lineEdit_2)
        self.kredi_comboBox_2 = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.kredi_comboBox_2.setObjectName(_fromUtf8("kredi_comboBox_2"))
        self.kredi_comboBox_2.addItem(_fromUtf8(""))
        self.kredi_comboBox_2.addItem(_fromUtf8(""))
        self.kredi_comboBox_2.addItem(_fromUtf8(""))
        self.kredi_comboBox_2.addItem(_fromUtf8(""))
        self.kredi_comboBox_2.addItem(_fromUtf8(""))
        self.kredi_comboBox_2.addItem(_fromUtf8(""))
        self.kredi_comboBox_2.addItem(_fromUtf8(""))
        self.kredi_comboBox_2.addItem(_fromUtf8(""))
        self.kredi_comboBox_2.addItem(_fromUtf8(""))
        self.kredi_comboBox_2.addItem(_fromUtf8(""))
        self.kredi_comboBox_2.addItem(_fromUtf8(""))
        self.ders_horizontalLayout_2.addWidget(self.kredi_comboBox_2)
        self.harf_notu_comboBox_2 = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.harf_notu_comboBox_2.setObjectName(_fromUtf8("harf_notu_comboBox_2"))
        self.harf_notu_comboBox_2.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_2.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_2.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_2.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_2.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_2.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_2.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_2.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_2.addItem(_fromUtf8(""))
        self.ders_horizontalLayout_2.addWidget(self.harf_notu_comboBox_2)
        self.sonuc_label_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.sonuc_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.sonuc_label_2.setObjectName(_fromUtf8("sonuc_label_2"))
        self.ders_horizontalLayout_2.addWidget(self.sonuc_label_2)
        self.verticalLayout.addLayout(self.ders_horizontalLayout_2)
        self.ders_horizontalLayout_3 = QtGui.QHBoxLayout()
        self.ders_horizontalLayout_3.setObjectName(_fromUtf8("ders_horizontalLayout_3"))
        self.ders_no_label_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ders_no_label_3.sizePolicy().hasHeightForWidth())
        self.ders_no_label_3.setSizePolicy(sizePolicy)
        self.ders_no_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.ders_no_label_3.setObjectName(_fromUtf8("ders_no_label_3"))
        self.ders_horizontalLayout_3.addWidget(self.ders_no_label_3)
        self.ders_adi_lineEdit_3 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ders_adi_lineEdit_3.sizePolicy().hasHeightForWidth())
        self.ders_adi_lineEdit_3.setSizePolicy(sizePolicy)
        self.ders_adi_lineEdit_3.setText(_fromUtf8(""))
        self.ders_adi_lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.ders_adi_lineEdit_3.setObjectName(_fromUtf8("ders_adi_lineEdit_3"))
        self.ders_horizontalLayout_3.addWidget(self.ders_adi_lineEdit_3)
        self.kredi_comboBox_3 = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.kredi_comboBox_3.setObjectName(_fromUtf8("kredi_comboBox_3"))
        self.kredi_comboBox_3.addItem(_fromUtf8(""))
        self.kredi_comboBox_3.addItem(_fromUtf8(""))
        self.kredi_comboBox_3.addItem(_fromUtf8(""))
        self.kredi_comboBox_3.addItem(_fromUtf8(""))
        self.kredi_comboBox_3.addItem(_fromUtf8(""))
        self.kredi_comboBox_3.addItem(_fromUtf8(""))
        self.kredi_comboBox_3.addItem(_fromUtf8(""))
        self.kredi_comboBox_3.addItem(_fromUtf8(""))
        self.kredi_comboBox_3.addItem(_fromUtf8(""))
        self.kredi_comboBox_3.addItem(_fromUtf8(""))
        self.kredi_comboBox_3.addItem(_fromUtf8(""))
        self.ders_horizontalLayout_3.addWidget(self.kredi_comboBox_3)
        self.harf_notu_comboBox_3 = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.harf_notu_comboBox_3.setObjectName(_fromUtf8("harf_notu_comboBox_3"))
        self.harf_notu_comboBox_3.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_3.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_3.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_3.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_3.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_3.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_3.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_3.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_3.addItem(_fromUtf8(""))
        self.ders_horizontalLayout_3.addWidget(self.harf_notu_comboBox_3)
        self.sonuc_label_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.sonuc_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.sonuc_label_3.setObjectName(_fromUtf8("sonuc_label_3"))
        self.ders_horizontalLayout_3.addWidget(self.sonuc_label_3)
        self.verticalLayout.addLayout(self.ders_horizontalLayout_3)
        self.ders_horizontalLayout_4 = QtGui.QHBoxLayout()
        self.ders_horizontalLayout_4.setObjectName(_fromUtf8("ders_horizontalLayout_4"))
        self.ders_no_label_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ders_no_label_4.sizePolicy().hasHeightForWidth())
        self.ders_no_label_4.setSizePolicy(sizePolicy)
        self.ders_no_label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.ders_no_label_4.setObjectName(_fromUtf8("ders_no_label_4"))
        self.ders_horizontalLayout_4.addWidget(self.ders_no_label_4)
        self.ders_adi_lineEdit_4 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ders_adi_lineEdit_4.sizePolicy().hasHeightForWidth())
        self.ders_adi_lineEdit_4.setSizePolicy(sizePolicy)
        self.ders_adi_lineEdit_4.setText(_fromUtf8(""))
        self.ders_adi_lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.ders_adi_lineEdit_4.setObjectName(_fromUtf8("ders_adi_lineEdit_4"))
        self.ders_horizontalLayout_4.addWidget(self.ders_adi_lineEdit_4)
        self.kredi_comboBox_4 = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.kredi_comboBox_4.setObjectName(_fromUtf8("kredi_comboBox_4"))
        self.kredi_comboBox_4.addItem(_fromUtf8(""))
        self.kredi_comboBox_4.addItem(_fromUtf8(""))
        self.kredi_comboBox_4.addItem(_fromUtf8(""))
        self.kredi_comboBox_4.addItem(_fromUtf8(""))
        self.kredi_comboBox_4.addItem(_fromUtf8(""))
        self.kredi_comboBox_4.addItem(_fromUtf8(""))
        self.kredi_comboBox_4.addItem(_fromUtf8(""))
        self.kredi_comboBox_4.addItem(_fromUtf8(""))
        self.kredi_comboBox_4.addItem(_fromUtf8(""))
        self.kredi_comboBox_4.addItem(_fromUtf8(""))
        self.kredi_comboBox_4.addItem(_fromUtf8(""))
        self.ders_horizontalLayout_4.addWidget(self.kredi_comboBox_4)
        self.harf_notu_comboBox_4 = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.harf_notu_comboBox_4.setObjectName(_fromUtf8("harf_notu_comboBox_4"))
        self.harf_notu_comboBox_4.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_4.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_4.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_4.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_4.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_4.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_4.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_4.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_4.addItem(_fromUtf8(""))
        self.ders_horizontalLayout_4.addWidget(self.harf_notu_comboBox_4)
        self.sonuc_label_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.sonuc_label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.sonuc_label_4.setObjectName(_fromUtf8("sonuc_label_4"))
        self.ders_horizontalLayout_4.addWidget(self.sonuc_label_4)
        self.verticalLayout.addLayout(self.ders_horizontalLayout_4)
        self.ders_horizontalLayout_5 = QtGui.QHBoxLayout()
        self.ders_horizontalLayout_5.setObjectName(_fromUtf8("ders_horizontalLayout_5"))
        self.ders_no_label_5 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ders_no_label_5.sizePolicy().hasHeightForWidth())
        self.ders_no_label_5.setSizePolicy(sizePolicy)
        self.ders_no_label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.ders_no_label_5.setObjectName(_fromUtf8("ders_no_label_5"))
        self.ders_horizontalLayout_5.addWidget(self.ders_no_label_5)
        self.ders_adi_lineEdit_5 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ders_adi_lineEdit_5.sizePolicy().hasHeightForWidth())
        self.ders_adi_lineEdit_5.setSizePolicy(sizePolicy)
        self.ders_adi_lineEdit_5.setText(_fromUtf8(""))
        self.ders_adi_lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.ders_adi_lineEdit_5.setObjectName(_fromUtf8("ders_adi_lineEdit_5"))
        self.ders_horizontalLayout_5.addWidget(self.ders_adi_lineEdit_5)
        self.kredi_comboBox_5 = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.kredi_comboBox_5.setObjectName(_fromUtf8("kredi_comboBox_5"))
        self.kredi_comboBox_5.addItem(_fromUtf8(""))
        self.kredi_comboBox_5.addItem(_fromUtf8(""))
        self.kredi_comboBox_5.addItem(_fromUtf8(""))
        self.kredi_comboBox_5.addItem(_fromUtf8(""))
        self.kredi_comboBox_5.addItem(_fromUtf8(""))
        self.kredi_comboBox_5.addItem(_fromUtf8(""))
        self.kredi_comboBox_5.addItem(_fromUtf8(""))
        self.kredi_comboBox_5.addItem(_fromUtf8(""))
        self.kredi_comboBox_5.addItem(_fromUtf8(""))
        self.kredi_comboBox_5.addItem(_fromUtf8(""))
        self.kredi_comboBox_5.addItem(_fromUtf8(""))
        self.ders_horizontalLayout_5.addWidget(self.kredi_comboBox_5)
        self.harf_notu_comboBox_5 = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.harf_notu_comboBox_5.setObjectName(_fromUtf8("harf_notu_comboBox_5"))
        self.harf_notu_comboBox_5.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_5.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_5.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_5.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_5.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_5.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_5.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_5.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_5.addItem(_fromUtf8(""))
        self.ders_horizontalLayout_5.addWidget(self.harf_notu_comboBox_5)
        self.sonuc_label_5 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.sonuc_label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.sonuc_label_5.setObjectName(_fromUtf8("sonuc_label_5"))
        self.ders_horizontalLayout_5.addWidget(self.sonuc_label_5)
        self.verticalLayout.addLayout(self.ders_horizontalLayout_5)
        self.ders_horizontalLayout_6 = QtGui.QHBoxLayout()
        self.ders_horizontalLayout_6.setObjectName(_fromUtf8("ders_horizontalLayout_6"))
        self.ders_no_label_6 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ders_no_label_6.sizePolicy().hasHeightForWidth())
        self.ders_no_label_6.setSizePolicy(sizePolicy)
        self.ders_no_label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.ders_no_label_6.setObjectName(_fromUtf8("ders_no_label_6"))
        self.ders_horizontalLayout_6.addWidget(self.ders_no_label_6)
        self.ders_adi_lineEdit_6 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ders_adi_lineEdit_6.sizePolicy().hasHeightForWidth())
        self.ders_adi_lineEdit_6.setSizePolicy(sizePolicy)
        self.ders_adi_lineEdit_6.setText(_fromUtf8(""))
        self.ders_adi_lineEdit_6.setAlignment(QtCore.Qt.AlignCenter)
        self.ders_adi_lineEdit_6.setObjectName(_fromUtf8("ders_adi_lineEdit_6"))
        self.ders_horizontalLayout_6.addWidget(self.ders_adi_lineEdit_6)
        self.kredi_comboBox_6 = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.kredi_comboBox_6.setObjectName(_fromUtf8("kredi_comboBox_6"))
        self.kredi_comboBox_6.addItem(_fromUtf8(""))
        self.kredi_comboBox_6.addItem(_fromUtf8(""))
        self.kredi_comboBox_6.addItem(_fromUtf8(""))
        self.kredi_comboBox_6.addItem(_fromUtf8(""))
        self.kredi_comboBox_6.addItem(_fromUtf8(""))
        self.kredi_comboBox_6.addItem(_fromUtf8(""))
        self.kredi_comboBox_6.addItem(_fromUtf8(""))
        self.kredi_comboBox_6.addItem(_fromUtf8(""))
        self.kredi_comboBox_6.addItem(_fromUtf8(""))
        self.kredi_comboBox_6.addItem(_fromUtf8(""))
        self.kredi_comboBox_6.addItem(_fromUtf8(""))
        self.ders_horizontalLayout_6.addWidget(self.kredi_comboBox_6)
        self.harf_notu_comboBox_6 = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.harf_notu_comboBox_6.setObjectName(_fromUtf8("harf_notu_comboBox_6"))
        self.harf_notu_comboBox_6.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_6.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_6.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_6.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_6.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_6.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_6.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_6.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_6.addItem(_fromUtf8(""))
        self.ders_horizontalLayout_6.addWidget(self.harf_notu_comboBox_6)
        self.sonuc_label_6 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.sonuc_label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.sonuc_label_6.setObjectName(_fromUtf8("sonuc_label_6"))
        self.ders_horizontalLayout_6.addWidget(self.sonuc_label_6)
        self.verticalLayout.addLayout(self.ders_horizontalLayout_6)
        self.ders_horizontalLayout_7 = QtGui.QHBoxLayout()
        self.ders_horizontalLayout_7.setObjectName(_fromUtf8("ders_horizontalLayout_7"))
        self.ders_no_label_7 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ders_no_label_7.sizePolicy().hasHeightForWidth())
        self.ders_no_label_7.setSizePolicy(sizePolicy)
        self.ders_no_label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.ders_no_label_7.setObjectName(_fromUtf8("ders_no_label_7"))
        self.ders_horizontalLayout_7.addWidget(self.ders_no_label_7)
        self.ders_adi_lineEdit_7 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ders_adi_lineEdit_7.sizePolicy().hasHeightForWidth())
        self.ders_adi_lineEdit_7.setSizePolicy(sizePolicy)
        self.ders_adi_lineEdit_7.setText(_fromUtf8(""))
        self.ders_adi_lineEdit_7.setAlignment(QtCore.Qt.AlignCenter)
        self.ders_adi_lineEdit_7.setObjectName(_fromUtf8("ders_adi_lineEdit_7"))
        self.ders_horizontalLayout_7.addWidget(self.ders_adi_lineEdit_7)
        self.kredi_comboBox_7 = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.kredi_comboBox_7.setObjectName(_fromUtf8("kredi_comboBox_7"))
        self.kredi_comboBox_7.addItem(_fromUtf8(""))
        self.kredi_comboBox_7.addItem(_fromUtf8(""))
        self.kredi_comboBox_7.addItem(_fromUtf8(""))
        self.kredi_comboBox_7.addItem(_fromUtf8(""))
        self.kredi_comboBox_7.addItem(_fromUtf8(""))
        self.kredi_comboBox_7.addItem(_fromUtf8(""))
        self.kredi_comboBox_7.addItem(_fromUtf8(""))
        self.kredi_comboBox_7.addItem(_fromUtf8(""))
        self.kredi_comboBox_7.addItem(_fromUtf8(""))
        self.kredi_comboBox_7.addItem(_fromUtf8(""))
        self.kredi_comboBox_7.addItem(_fromUtf8(""))
        self.ders_horizontalLayout_7.addWidget(self.kredi_comboBox_7)
        self.harf_notu_comboBox_7 = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.harf_notu_comboBox_7.setObjectName(_fromUtf8("harf_notu_comboBox_7"))
        self.harf_notu_comboBox_7.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_7.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_7.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_7.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_7.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_7.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_7.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_7.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_7.addItem(_fromUtf8(""))
        self.ders_horizontalLayout_7.addWidget(self.harf_notu_comboBox_7)
        self.sonuc_label_7 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.sonuc_label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.sonuc_label_7.setObjectName(_fromUtf8("sonuc_label_7"))
        self.ders_horizontalLayout_7.addWidget(self.sonuc_label_7)
        self.verticalLayout.addLayout(self.ders_horizontalLayout_7)
        self.ders_horizontalLayout_8 = QtGui.QHBoxLayout()
        self.ders_horizontalLayout_8.setObjectName(_fromUtf8("ders_horizontalLayout_8"))
        self.ders_no_label_8 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ders_no_label_8.sizePolicy().hasHeightForWidth())
        self.ders_no_label_8.setSizePolicy(sizePolicy)
        self.ders_no_label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.ders_no_label_8.setObjectName(_fromUtf8("ders_no_label_8"))
        self.ders_horizontalLayout_8.addWidget(self.ders_no_label_8)
        self.ders_adi_lineEdit_8 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ders_adi_lineEdit_8.sizePolicy().hasHeightForWidth())
        self.ders_adi_lineEdit_8.setSizePolicy(sizePolicy)
        self.ders_adi_lineEdit_8.setText(_fromUtf8(""))
        self.ders_adi_lineEdit_8.setAlignment(QtCore.Qt.AlignCenter)
        self.ders_adi_lineEdit_8.setObjectName(_fromUtf8("ders_adi_lineEdit_8"))
        self.ders_horizontalLayout_8.addWidget(self.ders_adi_lineEdit_8)
        self.kredi_comboBox_8 = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.kredi_comboBox_8.setObjectName(_fromUtf8("kredi_comboBox_8"))
        self.kredi_comboBox_8.addItem(_fromUtf8(""))
        self.kredi_comboBox_8.addItem(_fromUtf8(""))
        self.kredi_comboBox_8.addItem(_fromUtf8(""))
        self.kredi_comboBox_8.addItem(_fromUtf8(""))
        self.kredi_comboBox_8.addItem(_fromUtf8(""))
        self.kredi_comboBox_8.addItem(_fromUtf8(""))
        self.kredi_comboBox_8.addItem(_fromUtf8(""))
        self.kredi_comboBox_8.addItem(_fromUtf8(""))
        self.kredi_comboBox_8.addItem(_fromUtf8(""))
        self.kredi_comboBox_8.addItem(_fromUtf8(""))
        self.kredi_comboBox_8.addItem(_fromUtf8(""))
        self.ders_horizontalLayout_8.addWidget(self.kredi_comboBox_8)
        self.harf_notu_comboBox_8 = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.harf_notu_comboBox_8.setObjectName(_fromUtf8("harf_notu_comboBox_8"))
        self.harf_notu_comboBox_8.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_8.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_8.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_8.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_8.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_8.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_8.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_8.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_8.addItem(_fromUtf8(""))
        self.ders_horizontalLayout_8.addWidget(self.harf_notu_comboBox_8)
        self.sonuc_label_8 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.sonuc_label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.sonuc_label_8.setObjectName(_fromUtf8("sonuc_label_8"))
        self.ders_horizontalLayout_8.addWidget(self.sonuc_label_8)
        self.verticalLayout.addLayout(self.ders_horizontalLayout_8)
        self.ders_horizontalLayout_9 = QtGui.QHBoxLayout()
        self.ders_horizontalLayout_9.setObjectName(_fromUtf8("ders_horizontalLayout_9"))
        self.ders_no_label_9 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ders_no_label_9.sizePolicy().hasHeightForWidth())
        self.ders_no_label_9.setSizePolicy(sizePolicy)
        self.ders_no_label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.ders_no_label_9.setObjectName(_fromUtf8("ders_no_label_9"))
        self.ders_horizontalLayout_9.addWidget(self.ders_no_label_9)
        self.ders_adi_lineEdit_9 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ders_adi_lineEdit_9.sizePolicy().hasHeightForWidth())
        self.ders_adi_lineEdit_9.setSizePolicy(sizePolicy)
        self.ders_adi_lineEdit_9.setText(_fromUtf8(""))
        self.ders_adi_lineEdit_9.setAlignment(QtCore.Qt.AlignCenter)
        self.ders_adi_lineEdit_9.setObjectName(_fromUtf8("ders_adi_lineEdit_9"))
        self.ders_horizontalLayout_9.addWidget(self.ders_adi_lineEdit_9)
        self.kredi_comboBox_9 = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.kredi_comboBox_9.setObjectName(_fromUtf8("kredi_comboBox_9"))
        self.kredi_comboBox_9.addItem(_fromUtf8(""))
        self.kredi_comboBox_9.addItem(_fromUtf8(""))
        self.kredi_comboBox_9.addItem(_fromUtf8(""))
        self.kredi_comboBox_9.addItem(_fromUtf8(""))
        self.kredi_comboBox_9.addItem(_fromUtf8(""))
        self.kredi_comboBox_9.addItem(_fromUtf8(""))
        self.kredi_comboBox_9.addItem(_fromUtf8(""))
        self.kredi_comboBox_9.addItem(_fromUtf8(""))
        self.kredi_comboBox_9.addItem(_fromUtf8(""))
        self.kredi_comboBox_9.addItem(_fromUtf8(""))
        self.kredi_comboBox_9.addItem(_fromUtf8(""))
        self.ders_horizontalLayout_9.addWidget(self.kredi_comboBox_9)
        self.harf_notu_comboBox_9 = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.harf_notu_comboBox_9.setObjectName(_fromUtf8("harf_notu_comboBox_9"))
        self.harf_notu_comboBox_9.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_9.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_9.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_9.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_9.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_9.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_9.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_9.addItem(_fromUtf8(""))
        self.harf_notu_comboBox_9.addItem(_fromUtf8(""))
        self.ders_horizontalLayout_9.addWidget(self.harf_notu_comboBox_9)
        self.sonuc_label_9 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.sonuc_label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.sonuc_label_9.setObjectName(_fromUtf8("sonuc_label_9"))
        self.ders_horizontalLayout_9.addWidget(self.sonuc_label_9)
        self.verticalLayout.addLayout(self.ders_horizontalLayout_9)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 30, 1)
        self.ortalama_label = QtGui.QLabel(Dialog)
        self.ortalama_label.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ortalama_label.sizePolicy().hasHeightForWidth())
        self.ortalama_label.setSizePolicy(sizePolicy)
        self.ortalama_label.setMinimumSize(QtCore.QSize(0, 27))
        self.ortalama_label.setMaximumSize(QtCore.QSize(16777215, 27))
        self.ortalama_label.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(True)
        self.ortalama_label.setFont(font)
        self.ortalama_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ortalama_label.setObjectName(_fromUtf8("ortalama_label"))
        self.gridLayout.addWidget(self.ortalama_label, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setEnabled(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 18, 2, 1, 1)
        self.sinif_comboBox = QtGui.QComboBox(Dialog)
        self.sinif_comboBox.setEnabled(False)
        self.sinif_comboBox.setMaximumSize(QtCore.QSize(40, 16777215))
        self.sinif_comboBox.setObjectName(_fromUtf8("sinif_comboBox"))
        self.sinif_comboBox.addItem(_fromUtf8(""))
        self.sinif_comboBox.addItem(_fromUtf8(""))
        self.sinif_comboBox.addItem(_fromUtf8(""))
        self.sinif_comboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.sinif_comboBox, 22, 2, 1, 1)
        self.label = QtGui.QLabel(Dialog)
        self.label.setEnabled(True)
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 21, 2, 1, 1)
        self.ogrenim_durumu_comboBox = QtGui.QComboBox(Dialog)
        self.ogrenim_durumu_comboBox.setEnabled(False)
        self.ogrenim_durumu_comboBox.setObjectName(_fromUtf8("ogrenim_durumu_comboBox"))
        self.ogrenim_durumu_comboBox.addItem(_fromUtf8(""))
        self.ogrenim_durumu_comboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.ogrenim_durumu_comboBox, 19, 2, 1, 1)
        self.gno_durumu_checkBox = QtGui.QCheckBox(Dialog)
        self.gno_durumu_checkBox.setObjectName(_fromUtf8("gno_durumu_checkBox"))
        self.gridLayout.addWidget(self.gno_durumu_checkBox, 16, 2, 1, 1)
        self.line_2 = QtGui.QFrame(Dialog)
        self.line_2.setEnabled(True)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 20, 2, 1, 1)
        self.line = QtGui.QFrame(Dialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 25, 2, 1, 1)
        self.line_3 = QtGui.QFrame(Dialog)
        self.line_3.setEnabled(True)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout.addWidget(self.line_3, 17, 2, 1, 1)
        self.line_4 = QtGui.QFrame(Dialog)
        self.line_4.setEnabled(True)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout.addWidget(self.line_4, 15, 2, 1, 1)
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setEnabled(True)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 23, 2, 1, 1)
        self.donem_comboBox = QtGui.QComboBox(Dialog)
        self.donem_comboBox.setEnabled(False)
        self.donem_comboBox.setMaximumSize(QtCore.QSize(40, 16777215))
        self.donem_comboBox.setObjectName(_fromUtf8("donem_comboBox"))
        self.donem_comboBox.addItem(_fromUtf8(""))
        self.donem_comboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.donem_comboBox, 24, 2, 1, 1)
        self.temizle_pushButton = QtGui.QPushButton(Dialog)
        self.temizle_pushButton.setMinimumSize(QtCore.QSize(85, 22))
        self.temizle_pushButton.setAutoDefault(False)
        self.temizle_pushButton.setObjectName(_fromUtf8("temizle_pushButton"))
        self.gridLayout.addWidget(self.temizle_pushButton, 29, 2, 1, 1)
        self.hesapla_pushButton = QtGui.QPushButton(Dialog)
        self.hesapla_pushButton.setMinimumSize(QtCore.QSize(85, 22))
        self.hesapla_pushButton.setObjectName(_fromUtf8("hesapla_pushButton"))
        self.gridLayout.addWidget(self.hesapla_pushButton, 26, 2, 1, 1)
        self.ders_sil_pushButton = QtGui.QPushButton(Dialog)
        self.ders_sil_pushButton.setMinimumSize(QtCore.QSize(85, 22))
        self.ders_sil_pushButton.setAutoDefault(False)
        self.ders_sil_pushButton.setObjectName(_fromUtf8("ders_sil_pushButton"))
        self.gridLayout.addWidget(self.ders_sil_pushButton, 28, 2, 1, 1)
        self.ders_ekle_pushButton = QtGui.QPushButton(Dialog)
        self.ders_ekle_pushButton.setMinimumSize(QtCore.QSize(85, 22))
        self.ders_ekle_pushButton.setAutoDefault(False)
        self.ders_ekle_pushButton.setObjectName(_fromUtf8("ders_ekle_pushButton"))
        self.gridLayout.addWidget(self.ders_ekle_pushButton, 27, 2, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Ortalama Hesaplayıcı", None))
        self.ortalama_sonuc_label.setText(_translate("Dialog", "...", None))
        self.ders_no_label.setText(_translate("Dialog", "Ders No", None))
        self.ders_adi_label.setText(_translate("Dialog", "Ders Adı", None))
        self.kredi_label.setText(_translate("Dialog", "Kredi", None))
        self.harf_notu_label.setText(_translate("Dialog", "Harf Notu", None))
        self.kredi_harf_notu_label.setText(_translate("Dialog", "Kr x HN", None))
        self.ders_no_label_1.setText(_translate("Dialog", "1", None))
        self.ders_adi_lineEdit_1.setToolTip(_translate("Dialog", "Ders adlarını girmek zorunda değilsiniz fakat ders adını eklerseniz \n"
"aynı dersi tekrar ekleyip eklemediğini kontrol etmenize yardımcı olur.", None))
        self.kredi_comboBox_1.setItemText(0, _translate("Dialog", "0", None))
        self.kredi_comboBox_1.setItemText(1, _translate("Dialog", "1", None))
        self.kredi_comboBox_1.setItemText(2, _translate("Dialog", "2", None))
        self.kredi_comboBox_1.setItemText(3, _translate("Dialog", "3", None))
        self.kredi_comboBox_1.setItemText(4, _translate("Dialog", "4", None))
        self.kredi_comboBox_1.setItemText(5, _translate("Dialog", "5", None))
        self.kredi_comboBox_1.setItemText(6, _translate("Dialog", "6", None))
        self.kredi_comboBox_1.setItemText(7, _translate("Dialog", "7", None))
        self.kredi_comboBox_1.setItemText(8, _translate("Dialog", "8", None))
        self.kredi_comboBox_1.setItemText(9, _translate("Dialog", "9", None))
        self.kredi_comboBox_1.setItemText(10, _translate("Dialog", "10", None))
        self.harf_notu_comboBox_1.setItemText(0, _translate("Dialog", "AA", None))
        self.harf_notu_comboBox_1.setItemText(1, _translate("Dialog", "BA", None))
        self.harf_notu_comboBox_1.setItemText(2, _translate("Dialog", "BB", None))
        self.harf_notu_comboBox_1.setItemText(3, _translate("Dialog", "CB", None))
        self.harf_notu_comboBox_1.setItemText(4, _translate("Dialog", "CC", None))
        self.harf_notu_comboBox_1.setItemText(5, _translate("Dialog", "DC", None))
        self.harf_notu_comboBox_1.setItemText(6, _translate("Dialog", "DD", None))
        self.harf_notu_comboBox_1.setItemText(7, _translate("Dialog", "FD", None))
        self.harf_notu_comboBox_1.setItemText(8, _translate("Dialog", "FF", None))
        self.sonuc_label_1.setText(_translate("Dialog", "...", None))
        self.ders_no_label_2.setText(_translate("Dialog", "2", None))
        self.kredi_comboBox_2.setItemText(0, _translate("Dialog", "0", None))
        self.kredi_comboBox_2.setItemText(1, _translate("Dialog", "1", None))
        self.kredi_comboBox_2.setItemText(2, _translate("Dialog", "2", None))
        self.kredi_comboBox_2.setItemText(3, _translate("Dialog", "3", None))
        self.kredi_comboBox_2.setItemText(4, _translate("Dialog", "4", None))
        self.kredi_comboBox_2.setItemText(5, _translate("Dialog", "5", None))
        self.kredi_comboBox_2.setItemText(6, _translate("Dialog", "6", None))
        self.kredi_comboBox_2.setItemText(7, _translate("Dialog", "7", None))
        self.kredi_comboBox_2.setItemText(8, _translate("Dialog", "8", None))
        self.kredi_comboBox_2.setItemText(9, _translate("Dialog", "9", None))
        self.kredi_comboBox_2.setItemText(10, _translate("Dialog", "10", None))
        self.harf_notu_comboBox_2.setItemText(0, _translate("Dialog", "AA", None))
        self.harf_notu_comboBox_2.setItemText(1, _translate("Dialog", "BA", None))
        self.harf_notu_comboBox_2.setItemText(2, _translate("Dialog", "BB", None))
        self.harf_notu_comboBox_2.setItemText(3, _translate("Dialog", "CB", None))
        self.harf_notu_comboBox_2.setItemText(4, _translate("Dialog", "CC", None))
        self.harf_notu_comboBox_2.setItemText(5, _translate("Dialog", "DC", None))
        self.harf_notu_comboBox_2.setItemText(6, _translate("Dialog", "DD", None))
        self.harf_notu_comboBox_2.setItemText(7, _translate("Dialog", "FD", None))
        self.harf_notu_comboBox_2.setItemText(8, _translate("Dialog", "FF", None))
        self.sonuc_label_2.setText(_translate("Dialog", "...", None))
        self.ders_no_label_3.setText(_translate("Dialog", "3", None))
        self.kredi_comboBox_3.setItemText(0, _translate("Dialog", "0", None))
        self.kredi_comboBox_3.setItemText(1, _translate("Dialog", "1", None))
        self.kredi_comboBox_3.setItemText(2, _translate("Dialog", "2", None))
        self.kredi_comboBox_3.setItemText(3, _translate("Dialog", "3", None))
        self.kredi_comboBox_3.setItemText(4, _translate("Dialog", "4", None))
        self.kredi_comboBox_3.setItemText(5, _translate("Dialog", "5", None))
        self.kredi_comboBox_3.setItemText(6, _translate("Dialog", "6", None))
        self.kredi_comboBox_3.setItemText(7, _translate("Dialog", "7", None))
        self.kredi_comboBox_3.setItemText(8, _translate("Dialog", "8", None))
        self.kredi_comboBox_3.setItemText(9, _translate("Dialog", "9", None))
        self.kredi_comboBox_3.setItemText(10, _translate("Dialog", "10", None))
        self.harf_notu_comboBox_3.setItemText(0, _translate("Dialog", "AA", None))
        self.harf_notu_comboBox_3.setItemText(1, _translate("Dialog", "BA", None))
        self.harf_notu_comboBox_3.setItemText(2, _translate("Dialog", "BB", None))
        self.harf_notu_comboBox_3.setItemText(3, _translate("Dialog", "CB", None))
        self.harf_notu_comboBox_3.setItemText(4, _translate("Dialog", "CC", None))
        self.harf_notu_comboBox_3.setItemText(5, _translate("Dialog", "DC", None))
        self.harf_notu_comboBox_3.setItemText(6, _translate("Dialog", "DD", None))
        self.harf_notu_comboBox_3.setItemText(7, _translate("Dialog", "FD", None))
        self.harf_notu_comboBox_3.setItemText(8, _translate("Dialog", "FF", None))
        self.sonuc_label_3.setText(_translate("Dialog", "...", None))
        self.ders_no_label_4.setText(_translate("Dialog", "4", None))
        self.kredi_comboBox_4.setItemText(0, _translate("Dialog", "0", None))
        self.kredi_comboBox_4.setItemText(1, _translate("Dialog", "1", None))
        self.kredi_comboBox_4.setItemText(2, _translate("Dialog", "2", None))
        self.kredi_comboBox_4.setItemText(3, _translate("Dialog", "3", None))
        self.kredi_comboBox_4.setItemText(4, _translate("Dialog", "4", None))
        self.kredi_comboBox_4.setItemText(5, _translate("Dialog", "5", None))
        self.kredi_comboBox_4.setItemText(6, _translate("Dialog", "6", None))
        self.kredi_comboBox_4.setItemText(7, _translate("Dialog", "7", None))
        self.kredi_comboBox_4.setItemText(8, _translate("Dialog", "8", None))
        self.kredi_comboBox_4.setItemText(9, _translate("Dialog", "9", None))
        self.kredi_comboBox_4.setItemText(10, _translate("Dialog", "10", None))
        self.harf_notu_comboBox_4.setItemText(0, _translate("Dialog", "AA", None))
        self.harf_notu_comboBox_4.setItemText(1, _translate("Dialog", "BA", None))
        self.harf_notu_comboBox_4.setItemText(2, _translate("Dialog", "BB", None))
        self.harf_notu_comboBox_4.setItemText(3, _translate("Dialog", "CB", None))
        self.harf_notu_comboBox_4.setItemText(4, _translate("Dialog", "CC", None))
        self.harf_notu_comboBox_4.setItemText(5, _translate("Dialog", "DC", None))
        self.harf_notu_comboBox_4.setItemText(6, _translate("Dialog", "DD", None))
        self.harf_notu_comboBox_4.setItemText(7, _translate("Dialog", "FD", None))
        self.harf_notu_comboBox_4.setItemText(8, _translate("Dialog", "FF", None))
        self.sonuc_label_4.setText(_translate("Dialog", "...", None))
        self.ders_no_label_5.setText(_translate("Dialog", "5", None))
        self.kredi_comboBox_5.setItemText(0, _translate("Dialog", "0", None))
        self.kredi_comboBox_5.setItemText(1, _translate("Dialog", "1", None))
        self.kredi_comboBox_5.setItemText(2, _translate("Dialog", "2", None))
        self.kredi_comboBox_5.setItemText(3, _translate("Dialog", "3", None))
        self.kredi_comboBox_5.setItemText(4, _translate("Dialog", "4", None))
        self.kredi_comboBox_5.setItemText(5, _translate("Dialog", "5", None))
        self.kredi_comboBox_5.setItemText(6, _translate("Dialog", "6", None))
        self.kredi_comboBox_5.setItemText(7, _translate("Dialog", "7", None))
        self.kredi_comboBox_5.setItemText(8, _translate("Dialog", "8", None))
        self.kredi_comboBox_5.setItemText(9, _translate("Dialog", "9", None))
        self.kredi_comboBox_5.setItemText(10, _translate("Dialog", "10", None))
        self.harf_notu_comboBox_5.setItemText(0, _translate("Dialog", "AA", None))
        self.harf_notu_comboBox_5.setItemText(1, _translate("Dialog", "BA", None))
        self.harf_notu_comboBox_5.setItemText(2, _translate("Dialog", "BB", None))
        self.harf_notu_comboBox_5.setItemText(3, _translate("Dialog", "CB", None))
        self.harf_notu_comboBox_5.setItemText(4, _translate("Dialog", "CC", None))
        self.harf_notu_comboBox_5.setItemText(5, _translate("Dialog", "DC", None))
        self.harf_notu_comboBox_5.setItemText(6, _translate("Dialog", "DD", None))
        self.harf_notu_comboBox_5.setItemText(7, _translate("Dialog", "FD", None))
        self.harf_notu_comboBox_5.setItemText(8, _translate("Dialog", "FF", None))
        self.sonuc_label_5.setText(_translate("Dialog", "...", None))
        self.ders_no_label_6.setText(_translate("Dialog", "6", None))
        self.kredi_comboBox_6.setItemText(0, _translate("Dialog", "0", None))
        self.kredi_comboBox_6.setItemText(1, _translate("Dialog", "1", None))
        self.kredi_comboBox_6.setItemText(2, _translate("Dialog", "2", None))
        self.kredi_comboBox_6.setItemText(3, _translate("Dialog", "3", None))
        self.kredi_comboBox_6.setItemText(4, _translate("Dialog", "4", None))
        self.kredi_comboBox_6.setItemText(5, _translate("Dialog", "5", None))
        self.kredi_comboBox_6.setItemText(6, _translate("Dialog", "6", None))
        self.kredi_comboBox_6.setItemText(7, _translate("Dialog", "7", None))
        self.kredi_comboBox_6.setItemText(8, _translate("Dialog", "8", None))
        self.kredi_comboBox_6.setItemText(9, _translate("Dialog", "9", None))
        self.kredi_comboBox_6.setItemText(10, _translate("Dialog", "10", None))
        self.harf_notu_comboBox_6.setItemText(0, _translate("Dialog", "AA", None))
        self.harf_notu_comboBox_6.setItemText(1, _translate("Dialog", "BA", None))
        self.harf_notu_comboBox_6.setItemText(2, _translate("Dialog", "BB", None))
        self.harf_notu_comboBox_6.setItemText(3, _translate("Dialog", "CB", None))
        self.harf_notu_comboBox_6.setItemText(4, _translate("Dialog", "CC", None))
        self.harf_notu_comboBox_6.setItemText(5, _translate("Dialog", "DC", None))
        self.harf_notu_comboBox_6.setItemText(6, _translate("Dialog", "DD", None))
        self.harf_notu_comboBox_6.setItemText(7, _translate("Dialog", "FD", None))
        self.harf_notu_comboBox_6.setItemText(8, _translate("Dialog", "FF", None))
        self.sonuc_label_6.setText(_translate("Dialog", "...", None))
        self.ders_no_label_7.setText(_translate("Dialog", "7", None))
        self.kredi_comboBox_7.setItemText(0, _translate("Dialog", "0", None))
        self.kredi_comboBox_7.setItemText(1, _translate("Dialog", "1", None))
        self.kredi_comboBox_7.setItemText(2, _translate("Dialog", "2", None))
        self.kredi_comboBox_7.setItemText(3, _translate("Dialog", "3", None))
        self.kredi_comboBox_7.setItemText(4, _translate("Dialog", "4", None))
        self.kredi_comboBox_7.setItemText(5, _translate("Dialog", "5", None))
        self.kredi_comboBox_7.setItemText(6, _translate("Dialog", "6", None))
        self.kredi_comboBox_7.setItemText(7, _translate("Dialog", "7", None))
        self.kredi_comboBox_7.setItemText(8, _translate("Dialog", "8", None))
        self.kredi_comboBox_7.setItemText(9, _translate("Dialog", "9", None))
        self.kredi_comboBox_7.setItemText(10, _translate("Dialog", "10", None))
        self.harf_notu_comboBox_7.setItemText(0, _translate("Dialog", "AA", None))
        self.harf_notu_comboBox_7.setItemText(1, _translate("Dialog", "BA", None))
        self.harf_notu_comboBox_7.setItemText(2, _translate("Dialog", "BB", None))
        self.harf_notu_comboBox_7.setItemText(3, _translate("Dialog", "CB", None))
        self.harf_notu_comboBox_7.setItemText(4, _translate("Dialog", "CC", None))
        self.harf_notu_comboBox_7.setItemText(5, _translate("Dialog", "DC", None))
        self.harf_notu_comboBox_7.setItemText(6, _translate("Dialog", "DD", None))
        self.harf_notu_comboBox_7.setItemText(7, _translate("Dialog", "FD", None))
        self.harf_notu_comboBox_7.setItemText(8, _translate("Dialog", "FF", None))
        self.sonuc_label_7.setText(_translate("Dialog", "...", None))
        self.ders_no_label_8.setText(_translate("Dialog", "8", None))
        self.kredi_comboBox_8.setItemText(0, _translate("Dialog", "0", None))
        self.kredi_comboBox_8.setItemText(1, _translate("Dialog", "1", None))
        self.kredi_comboBox_8.setItemText(2, _translate("Dialog", "2", None))
        self.kredi_comboBox_8.setItemText(3, _translate("Dialog", "3", None))
        self.kredi_comboBox_8.setItemText(4, _translate("Dialog", "4", None))
        self.kredi_comboBox_8.setItemText(5, _translate("Dialog", "5", None))
        self.kredi_comboBox_8.setItemText(6, _translate("Dialog", "6", None))
        self.kredi_comboBox_8.setItemText(7, _translate("Dialog", "7", None))
        self.kredi_comboBox_8.setItemText(8, _translate("Dialog", "8", None))
        self.kredi_comboBox_8.setItemText(9, _translate("Dialog", "9", None))
        self.kredi_comboBox_8.setItemText(10, _translate("Dialog", "10", None))
        self.harf_notu_comboBox_8.setItemText(0, _translate("Dialog", "AA", None))
        self.harf_notu_comboBox_8.setItemText(1, _translate("Dialog", "BA", None))
        self.harf_notu_comboBox_8.setItemText(2, _translate("Dialog", "BB", None))
        self.harf_notu_comboBox_8.setItemText(3, _translate("Dialog", "CB", None))
        self.harf_notu_comboBox_8.setItemText(4, _translate("Dialog", "CC", None))
        self.harf_notu_comboBox_8.setItemText(5, _translate("Dialog", "DC", None))
        self.harf_notu_comboBox_8.setItemText(6, _translate("Dialog", "DD", None))
        self.harf_notu_comboBox_8.setItemText(7, _translate("Dialog", "FD", None))
        self.harf_notu_comboBox_8.setItemText(8, _translate("Dialog", "FF", None))
        self.sonuc_label_8.setText(_translate("Dialog", "...", None))
        self.ders_no_label_9.setText(_translate("Dialog", "9", None))
        self.kredi_comboBox_9.setItemText(0, _translate("Dialog", "0", None))
        self.kredi_comboBox_9.setItemText(1, _translate("Dialog", "1", None))
        self.kredi_comboBox_9.setItemText(2, _translate("Dialog", "2", None))
        self.kredi_comboBox_9.setItemText(3, _translate("Dialog", "3", None))
        self.kredi_comboBox_9.setItemText(4, _translate("Dialog", "4", None))
        self.kredi_comboBox_9.setItemText(5, _translate("Dialog", "5", None))
        self.kredi_comboBox_9.setItemText(6, _translate("Dialog", "6", None))
        self.kredi_comboBox_9.setItemText(7, _translate("Dialog", "7", None))
        self.kredi_comboBox_9.setItemText(8, _translate("Dialog", "8", None))
        self.kredi_comboBox_9.setItemText(9, _translate("Dialog", "9", None))
        self.kredi_comboBox_9.setItemText(10, _translate("Dialog", "10", None))
        self.harf_notu_comboBox_9.setItemText(0, _translate("Dialog", "AA", None))
        self.harf_notu_comboBox_9.setItemText(1, _translate("Dialog", "BA", None))
        self.harf_notu_comboBox_9.setItemText(2, _translate("Dialog", "BB", None))
        self.harf_notu_comboBox_9.setItemText(3, _translate("Dialog", "CB", None))
        self.harf_notu_comboBox_9.setItemText(4, _translate("Dialog", "CC", None))
        self.harf_notu_comboBox_9.setItemText(5, _translate("Dialog", "DC", None))
        self.harf_notu_comboBox_9.setItemText(6, _translate("Dialog", "DD", None))
        self.harf_notu_comboBox_9.setItemText(7, _translate("Dialog", "FD", None))
        self.harf_notu_comboBox_9.setItemText(8, _translate("Dialog", "FF", None))
        self.sonuc_label_9.setText(_translate("Dialog", "...", None))
        self.ortalama_label.setText(_translate("Dialog", "Ortalama", None))
        self.label_2.setText(_translate("Dialog", "Öğrenim Durumu:", None))
        self.sinif_comboBox.setItemText(0, _translate("Dialog", "1", None))
        self.sinif_comboBox.setItemText(1, _translate("Dialog", "2", None))
        self.sinif_comboBox.setItemText(2, _translate("Dialog", "3", None))
        self.sinif_comboBox.setItemText(3, _translate("Dialog", "4", None))
        self.label.setToolTip(_translate("Dialog", "Şu an hangi sınıfta iseniz onu seçiniz. \n"
" Hangi sınıfa geçtiğinizin bilgisi istenmiyor.", None))
        self.label.setText(_translate("Dialog", "Sınıf : ", None))
        self.ogrenim_durumu_comboBox.setItemText(0, _translate("Dialog", "Lisans", None))
        self.ogrenim_durumu_comboBox.setItemText(1, _translate("Dialog", "Önlisans", None))
        self.gno_durumu_checkBox.setToolTip(_translate("Dialog", "DD/DC harf notuna sahip derslerden geçip geçmediğinizi öğrenmenize yarar.", None))
        self.gno_durumu_checkBox.setText(_translate("Dialog", "GNO Durumu", None))
        self.label_3.setToolTip(_translate("Dialog", "Şu an hangi dönemi bitirdiyseniz veya bitirecekseniz onu seçiniz.", None))
        self.label_3.setText(_translate("Dialog", "Dönem :", None))
        self.donem_comboBox.setItemText(0, _translate("Dialog", "1", None))
        self.donem_comboBox.setItemText(1, _translate("Dialog", "2", None))
        self.temizle_pushButton.setText(_translate("Dialog", "Temizle", None))
        self.temizle_pushButton.setShortcut(_translate("Dialog", "Backspace", None))
        self.hesapla_pushButton.setText(_translate("Dialog", "Hesapla", None))
        self.hesapla_pushButton.setShortcut(_translate("Dialog", "Return", None))
        self.ders_sil_pushButton.setText(_translate("Dialog", "Ders Sil", None))
        self.ders_sil_pushButton.setShortcut(_translate("Dialog", "-", None))
        self.ders_ekle_pushButton.setText(_translate("Dialog", "Ders Ekle", None))
        self.ders_ekle_pushButton.setShortcut(_translate("Dialog", "+", None))

